# Generated by Django 4.2.1 on 2023-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
